### ISSUE TITLE
Goby's String class should be multilingual-conscious

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#174]
Current strings are counted as byte:

```ruby
puts("🍣".size)   # => 4
puts("我学".size) # => 6
puts("🍣".length)   # => 4
puts("我学".length) # => 6
```

This comes from the `string` type in Go.

```go
type StringObject struct {
	Class *RString
	Value string
}
```

I'd suggest that changing `string` type to `rune` type or like that as a default, to support `each` on multilingual strings. 

------------
**memorandum:** Looks like the minimum specification of Goby is needed soon: 

- Goby's encoding is implicitly fixed to UTF-8, while Ruby's String has `#encoding` to change with. 
- Perhaps character literal like `"\u{00A0}"` or numeric literal like `1_000_000` are going to be needed in the future, and such literals would affect lexer/parser implementations. 
- Implementing without specification would lead inconsistency among implementations.

FYI: Ruby had long been missing the official specification until ISO/IEC 30170:2012 was established https://www.iso.org/standard/59579.html.
The latest specification http://kikakurui.com/x3/X3017-2013-01.html is unfortunately written in Japanese.

**Comment by Maxwell-Alexius** [comment]
Yeah, I do found out that `rune` type of string did help tackling some sort of character problems. When printing length of string, it counts the `bytes` of the string. However, `rune` type determines the character by its *codepoint*. See more on [this article](https://blog.golang.org/strings)

```
package main

import "fmt"

func main() {
    const sample = "🍣"
    fmt.Println(len(sample)) // => 4
    fmt.Println(len([]rune(sample)))  // => 1
}
```

I do think we can convert `string` to `[]rune` type but not for all of the string api methods. Maybe we can *correct the methods that needs to have precise conversion* which involves with **string indexing operation**.

For instance, `String#insert` need to specify the index of the string to insert an input string. However, `String#include` might not need to do the conversion because it just need to match the bytes of the string but not counting or modifying the index of the string.

Also, we can add multilingual or other bizarre unicode character or string to test the string methods. This deserves another PR.

**Comment by Maxwell-Alexius** [comment]
Close this issue with PR #254 merged
