### ISSUE TITLE
Channel usage

### ISSUE THREAD

**Issue by pannous** [goby-lang/goby#362]
how do I use goby channels correctly?

This doesn't work as expected:
```ruby
c = Channel.new
thread do
  c.deliver(0)
end

1000.times do
  thread do
    c.deliver(c.receive+1)
  end
end
puts(c.receive) #<1000 :(
```

**Comment by st0012** [comment]
This expected, if you write corresponding Go program it will behave the same.

```go
package main

import (
	"fmt"
)

func main() {
	c := make(chan (int))

	go func() {
		c <- 0
	}()

	for i := 0; i < 1000; i++ {
		go func() {
			c <- (<-c + 1)
		}(.
	}

	fmt.Println(<-c)
}
```

This is because some thread's execution is slower than the speed program reaching `puts(c.receive)`. If you want this program behaves as you expected, you should block the main thread until last thread finishes. But that'd be meaningless for using thread.

**Comment by pannous** [comment]
ah, makes sense, thanks

**Comment by st0012** [comment]
BTW @pannous  you should join our slack: https://goby-lang-slackin.herokuapp.com 😄
