### ISSUE TITLE
Arithmetic operations with multiple right values are allowed

### ISSUE THREAD

**Issue by saveriomiroddi** [goby-lang/goby#444]
In Goby, it's allowed to perform an arithmetic operation with two right values:

    1 * *[2, 3] #=> 2

I think this should be forbidden; if so, probably the best place to forbid this is at parser level, otherwise, argument checks should be added for each operation method.

**Comment by st0012** [comment]
This is a bug and should be fixed in Parser

**Comment by ear7h** [comment]
I was looking into this today and I found it only happens with * *, not ** or other operators. I think it's caused by the registering of asterisk as a prefix expression.

Removing [this line](https://github.com/goby-lang/goby/blob/master/compiler/parser/parser.go#L69) and adding the following line seems to fix this specific issue. But running go test ./... yields several parser related test failures before a SIGSEGV. I'm willing to work on this but unsure how to proceed.

```go
	p.registerInfix(token.Asterisk, p.parseInfixExpression)
```

**Comment by st0012** [comment]
@ear7h Maybe adding check inside `p.parseInfixExpression`?
`* *` is two tokens for the parser while `**` is one. So when we proceed to the second `*` the left expression will also be `*`, and then we can know user are using it in the wrong way
