### ISSUE TITLE
Create Goby plugin for editors

### ISSUE THREAD

**Issue by st0012** [goby-lang/goby#635]
Because our syntax is compatible with Ruby's, so basically we can all just clone and modify Ruby's plugin (mainly for keywords)

## Editors to support
- [x] `Vim`, can just modify https://github.com/vim-ruby/vim-ruby
- [x] `Sublime`
- [ ] `VSCode`

## Keywords that need to be supported
- def
- true
- false
- nil
- if
- elsif
- else
- case
- when
- return
- self
- end
- while
- do
- yield
- get_block
- next
- break
- class
- module

**Comment by saveriomiroddi** [comment]
If somebody takes care of the VSCode and Emacs ones, we're st.

**Comment by hachi8833** [comment]
Memorandum: JetBrains' [Plugin development guide](https://www.jetbrains.com/help/idea/plugin-development-guidelines.html#d389723e7) would help to create a plugin for Goland or other JetBrains IDE.

Well, current [Ruby plugin](https://plugins.jetbrains.com/plugin/1293-ruby) contains .jar files 😢

**Comment by saveriomiroddi** [comment]
JAR files are simple ZIP archives, so that they can be opened and inspected. However, the IDEA plugins are quite big in size and functionality, so there's a huge amount of stuff inside :smile: 
Nonetheless, for the audacious one who's going to dig in, it should be relatively easy to isolate the syntax definition file, and clone only that into a new, separate plugin (as I did with "Only Goby").

**Comment by st0012** [comment]
This shouldn't be a priority now actually, so closing it.
